spring:
    application:
        name: core
    datasource:
        url: jdbc:h2:mem:default;MODE=MySQL
        schema: classpath:core.sql

mybatis:
    type-aliases-package: io.github.thinkframework.commons.*.domain
#    type-handlers-package: com.example.typehandler
    configuration:
        map-underscore-to-camel-case: true
#        default-fetch-size: 100
#        default-statement-timeout: 30
